### ISSUE TITLE
Feature: Forgot Password

### ISSUE THREAD

**Issue by nyomansunima** [nyomansunima/doen#14]
# About

Forget the password page. Allow the user to reset the password with the new one by passing the email they used in the app. 

There are several steps to passed in included: 
- Email Input
- Verify Code
- Reset Password
- Finish

## Tasks

- [ ] Create UI Design
- [ ] Create Web Form frontend
- [ ] Start implement logic
